# Generated by Django 2.2.7 on 2020-09-15 16:36

import Chat.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('userSession', models.CharField(max_length=100)),
                ('botName', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=Chat.models.upload_location)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 22, 6, 47, 918038))),
                ('flag', models.BooleanField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='aimlfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=Chat.models.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templateName', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='templateProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.IntegerField(default=0)),
                ('property_name', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_last', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
