# Generated by Django 2.2.7 on 2020-09-15 16:38

import Chat.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addBot_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100, unique=True)),
                ('userSession', models.CharField(max_length=100)),
                ('botName', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to=Chat.models.upload_location)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 15, 22, 8, 5, 184887))),
                ('flag', models.BooleanField(blank=True, default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='addBot',
        ),
    ]
